# Generated by Django 4.0.6 on 2022-07-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_templates_websites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
        migrations.RenameModel(
            old_name='Websites',
            new_name='Website',
        ),
    ]
