# Generated by Django 4.0.6 on 2022-07-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_templates_template_rename_websites_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Completed', 'Completed'), ('Hosted', 'Hosted')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('porfolio', 'porfolio'), ('ecommerce', 'ecommerce'), ('education', 'education'), ('health', 'health')], max_length=200, null=True),
        ),
    ]
