# Generated by Django 4.0.6 on 2022-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tag_website_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='tags',
        ),
        migrations.AddField(
            model_name='template',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
