# Generated by Django 4.0.6 on 2022-07-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_website_tags_template_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
    ]
