# Generated by Django 4.0.6 on 2022-07-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_user_alter_template_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profiel_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
