# Generated by Django 4.0.6 on 2022-07-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_profiel_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profiel_pic',
            new_name='profile_pic',
        ),
    ]
